;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-insert-item
        TeX-insert-backslash
        c-electric-lt-gt
        cdlatex-dollar
        cdlatex-math-modify
        cdlatex-math-symbol
        cdlatex-pbb
        cdlatex-sub-superscript
        hungry-delete-backward
        hungry-delete-forward
        mouse-set-region
        ))

(setq mc/cmds-to-run-once
      '(
        mouse-buffer-menu
        ))
